version: "3.8"

services:
  openems_edge:
    image: edge:latest
    container_name: openems_edge
    hostname: openems_edge
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
  openems_backend:
    image: backend:latest
    container_name: openems_backend
    hostname: openems_backend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
  openems_ui:
    image: ui:latest
    container_name: openems_ui
    hostname: openems_ui
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
