version: "3.8"

services:
  openems_edge:
    image: edge:latest
    container_name: openems_edge
    hostname: openems_edge
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
  openems_ui:
    image: ui:latest
    container_name: openems_ui
    hostname: openems_ui
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
