version: "3.8"

services:
  openems:
#    image: openems:latest
    image: 373f4d140d8d
    container_name: openems
    hostname: openems
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker/openems_stack/conf:/config:rw
      - /docker/openems_stack/data:/data:rw
      - /docker/openems_stack/log:/log:rw
    networks:
      macvlan-iot:
        ipv4_address: 10.13.12.32
      db:
      mqtt:
      modbus:
      proxy:

networks:
  macvlan-iot:
    external: true
  mqtt:
    external: true
  db:
    external: true
  modbus:
    external: true
  proxy:
    external: true
