version: "3.8"

services:
  openems_edge:
    image: edge:latest
    container_name: openems_edge
    hostname: openems_edge
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker/openems_stack/edge/conf:/config:rw
      - /docker/openems_stack/edge/data:/data:rw
  openems_edgeui:
    image: edgeui:latest
    container_name: openems_edgeui
    hostname: openems_edgeui
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker/openems_stack/edgeui/conf:/config:rw
      - /docker/openems_stack/edgeui/log:/log:rw