version: "3.8"

services:
  openems_ui:
    image: openems/ui:latest
    container_name: openems_ui
    hostname: openems_ui
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker/openems_stack/ui/conf:/config:rw
      - /docker/openems_stack/ui/log:/log:rw
