version: "3.8"

services:
  openems_edge:
    image: openems/edge:latest
    container_name: openems_edge
    hostname: openems_edge
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker/openems_stack/edge/conf:/config:rw
      - /docker/openems_stack/edge/data:/data:rw
